language: php
php:
- 7.1
- 7.2
before_script:
- composer self-update
- echo "{\"http-basic\":{\"repo.magento.com\":{\"username\":\"${MAGENTO_USERNAME}\",\"password\":\"${MAGENTO_PASSWORD}\"}}}" > auth.json
- phpenv config-rm xdebug.ini
- composer install --no-interaction --prefer-dist
- php vendor/bin/phpcs --config-set ignore_warnings_on_exit 1
- php vendor/bin/phpcs --config-set show_warnings 0
script:
- php vendor/bin/grumphp run
env:
  global:
    secure: ca9b2KdrXAqjOHx05ZV+2njjpt0SkKfRc8kFLh30Tt8XSndD0xPTtVjfAb2Dqbr1RV52fKi3ls0e4YgNRQwUK8AyM3OckswSyooGQWN0VtPVS8m7ZPoXGxnSaVarD2X/2JPLuCvPjN8LL+X5IBU6qqWqngjDlLore3CDRH+myufCQBbvh2I5A7VipTksJZgcYDO/QveNO8jSiuNGCT0o8DXc9hfDff7UxhbrcQ6P6w5n3N4kn0R7YWiO5RcaRiMEEZAkuA2hWF1HYAK3KjGjiMuZnvov5eDFYtfu/JmL/roHdQryoD4ir1QbKY2ZCHGTAJPGNN4/H2yFTqbhkx4eRhQGabMz0ok1Qq4nRwIpdaB6/3A2je/yGmHxczUyJ1s1Qkf5+LwCtkQ7GWVFbBD1WmK2CkbuzvBK83oa8wXFKp6N8flSz4GAs/zcbOZUaztSHVPsSuU43lS+nuuyZxIEvIruhbiybGHGWdwA66sl29rJ/5FRqJ9NmrlX+eryAd0zFf+sa2SDeBnWmxvJdX2zX3JG9YsJShHSbKhi5bPXCY4uLJK/mptVuoL497GIvPtb1iGJ2OZx75WvlI3q/LgHiV7b+TjnrkWvDB5MwNjhgiCMN7eMZIQ+SxSlVvtOgXMPDvDhtS6imZ1+fP3KQ+F1bCzuoZ36kF81OQhGtiXB30Q=
